<?php 
return array (
  'pigcms_debug' => '0',
  'site_name' => '好资源多用户微信营销系统',
  'site_title' => '好资源多用户微信营销系统',
  'site_logo' => 'tpl/Home/pigcms/common/images/logo-pigcms.png',
  'site_url' => 'http://www.goodziyuan.com',
  'site_twm' => '',
  'site_my' => '小资源',
  'server_key' => '5b4ee4db1ff2583e2c4e3d0db6f67be0',
  'appid' => 'wx347c99d4af110194',
  'secret' => '76c1becfee9c1cef5c769515bcb497c8',
  'server_topdomain' => 'goodziyuan.com',
  'connectout' => '已超出限制',
  'ischeckuser' => 'false',
  'reg_needmp' => 'true',
  'open_biz' => '0',
  'reg_groupid' => '4',
  'reg_validdays' => '30',
  'router_key' => 'r7omtsKnmtfB5eB7opmr',
  'ipc' => '蜀ICP备12023338号-1',
  'site_qq' => '846961669',
  'site_mp' => '18888888888',
  'baidu_map' => '1',
  'baidu_map_api' => 'Zi1YeleFkST1oEd4Eeom3Dx1',
  'site_email' => '846961669@qq.com',
  'keyword' => '微信公众平台接口开发、托管、营销活动、二次开发',
  'content' => '好资源多用户微信营销系统',
  'countsz' => '',
  'copyright' => 'Copyright (c) 2015 好资源源码 版权所有',
  'close_help' => '0',
  'close_user_notice' => '0',
  'emergent_mode' => '0',
  'update_server' => 'http://up.pigcms.cn/',
  'encryption' => NULL,
);